-- made by goofyscreech820 --
-- wolf v1 ( 99 nights in the forest )


-- i would appreciate if you would tag me on yt if you make a vid about the model. my channel: @goofyscreechOffical
-- might aswell play my dead rails games, and follow me on roblox!
-- tag me in whatever game you make with this model please
-------------------------------------------------------------------------------------------------------------------

-- anyone who created this free model except goofyscreech820 is a bot or faker.

-- TUTORIAL HOW TO USE --

-- Step 1: you see the main script inside the wolf model? click it, there is a anim id.
-- Step 2: to make the walk animation, open "AVATAR" on the top of your screen
-- Step 3: Click Animation Editor, then click the bunny, there will be "wolfwalk" animation.
-- Step 4: Republish the animation with animation looping on, so it works forever
-- Step 5: once published, copy the id, enter the main script, change the id and there you have it.

-- Thats all! -- 

-- This model wasnt stolen or whatever, was made entirely by myself, with more to come soon.
-- credits to 99 nights in the forest, or grandma's favorite games however.
