local BLUE = Color3.fromRGB(0, 85, 255)

return {
	DARK1 = Color3.fromRGB(13, 13, 18),
	DARK1_ALT = Color3.fromRGB(19, 19, 27),
	DARK2 = Color3.fromRGB(26, 26, 35),
	DARK2_ALT = Color3.fromRGB(32, 32, 44),
	DARK3 = Color3.fromRGB(39, 39, 53),
	DARK3_ALT = Color3.fromRGB(45, 45, 62),
	DARK4 = Color3.fromRGB(51, 51, 71),
	DARK4_ALT = Color3.fromRGB(58, 58, 80),
	DARK5 = Color3.fromRGB(64, 64, 89),
	DARK5_ALT = Color3.fromRGB(71, 71, 98),

	BLACK1 = Color3.fromHex("#000000"),
	WHITE1 = Color3.fromHex("#ffffff"),

	BLUE1 = BLUE,
	RED1 = Color3.fromRGB(255, 0, 0),
	ORANGE1 = Color3.fromRGB(255, 140, 0),
	YELLOW1 = Color3.fromRGB(255, 204, 0),
	GREEN1 = Color3.fromRGB(45, 144, 45),

	BUTTON = Color3.fromRGB(39, 39, 53),
	BUTTON_BRIGHTER = Color3.fromRGB(51, 51, 71),
	BUTTON_ACTIVE_BLUE = BLUE,
	BUTTON_ACTIVE_GREEN = Color3.fromRGB(45, 144, 45),
}